### ISSUE TITLE
Files not sorted as expected

### ISSUE THREAD

**Issue by frmarchal** [marksteele/mysql-dba-tools#1]
Hello,

At line 164 (https://github.com/marksteele/mysql-dba-tools/blob/master/rotatebinlogs.pl#L164), I believe the purpose is to sort the bin log files from the lowest number to the highest:

```
   my @files = map { $_->[0] } sort { $a->[1] <=> $b->[1] } map { [$_, /\.(\d+)$/] } grep {/^$prefix-bin\.\d+\.gz$/} readdir(D);
```

It doesn't work because the second map lacks a .gz at the end of the regular expression. It should be written like this:

```
my @files = map { $_->[0] } sort { $a->[1] <=> $b->[1] } map { [$_, /\.(\d+)\.gz$/] } grep {/^$prefix-bin\.\d+\.gz$/} readdir(D);
```

Note that it isn't a critical bug. The files are still processed but in a random order.

BTW, thanks for sharing your code!

**Comment by marksteele** [comment]
Nope, that will work as expected. You have to read it left to right (grep first, then first map extracts the digits, then second map sorts on that number).

**Comment by marksteele** [comment]
You're right!

Fixed.
